package com.diyiliu.server.support.ui;

import com.diyiliu.common.util.UIHepler;
import com.diyiliu.server.netty.ChatServer;

import javax.swing.*;
import java.awt.event.ActionEvent;

/**
 * Description: ServerUI
 * Author: DIYILIU
 * Update: 2018-03-01 14:25
 */
public class ServerUI extends javax.swing.JFrame {

    private  ChatServer server;

    /**
     * Creates new form ServerUI
     */
    public ServerUI() {
        UIHepler.beautify("Nimbus");
        initComponents();

        UIHepler.setCenter(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        lbPort = new javax.swing.JLabel();
        tfPort = new javax.swing.JTextField();
        btnOperator = new javax.swing.JButton();
        sclpn = new javax.swing.JScrollPane();
        ltUser = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("服务器");
        setResizable(false);

        lbPort.setText("端口号：");

        tfPort.setText("8888");

        btnOperator.setText("启动");
        btnOperator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));


        btnOperator.addActionListener((ActionEvent e) -> {
            String text = btnOperator.getText();
            if ("启动".equals(text)){
                server = new ChatServer();
                server.setServerUI(this);

                int port = Integer.parseInt(tfPort.getText().trim());
                server.setPort(port);
                server.start();
                tfPort.setEnabled(false);

                btnOperator.setText("停止");
            }else {
                if (server != null){
                    server.shutdown();
                    tfPort.setEnabled(true);

                    btnOperator.setText("启动");
                }
            }
        });

        sclpn.setBorder(null);
        ltUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "在线列表", 0, 0, new java.awt.Font("隶书", 0, 12))); // NOI18N
        ltUser.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        sclpn.setViewportView(ltUser);

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
                pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnMainLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sclpn)
                                        .addGroup(pnMainLayout.createSequentialGroup()
                                                .addComponent(lbPort)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfPort, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnOperator)))
                                .addContainerGap())
        );
        pnMainLayout.setVerticalGroup(
                pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnMainLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbPort)
                                        .addComponent(tfPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnOperator))
                                .addGap(18, 18, 18)
                                .addComponent(sclpn, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnOperator;
    private javax.swing.JList<String> ltUser;
    private javax.swing.JLabel lbPort;
    private javax.swing.JPanel pnMain;
    private javax.swing.JScrollPane sclpn;
    private javax.swing.JTextField tfPort;
    // End of variables declaration

    public void init() {
        java.awt.EventQueue.invokeLater(() ->
                this.setVisible(true)
        );
    }

    public JList<String> getLtUser() {
        return ltUser;
    }
}

