package com.diyiliu.client.support.ui;

import com.diyiliu.client.netty.ChatClient;
import com.diyiliu.common.util.UIHepler;
import org.apache.commons.lang3.StringUtils;

import java.awt.*;
import java.awt.event.ActionEvent;

public class LoginUI extends javax.swing.JFrame {

    private ChatClient client;

    /**
     * Creates new form LoginUI
     */
    public LoginUI() {
        UIHepler.beautify("Nimbus");
        initComponents();

        UIHepler.setCenter(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        lbHost = new javax.swing.JLabel();
        lbPort = new javax.swing.JLabel();
        lbAccount = new javax.swing.JLabel();
        tfHost = new javax.swing.JTextField("192.168.10.10");
        tfPort = new javax.swing.JTextField("8888");
        tfAccount = new javax.swing.JTextField();
        lbTitle = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setTitle("登录主机");
        setResizable(false);

        pnMain.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbHost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbHost.setText("主机：");

        lbPort.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPort.setText("端口：");

        lbAccount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbAccount.setText("账号：");

        lbTitle.setFont(new java.awt.Font("隶书", 1, 18)); // NOI18N
        lbTitle.setText("欢迎登录");

        btnLogin.setText("登录");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnLogin.addActionListener((ActionEvent e) -> {
            String host = tfHost.getText().trim();
            String port = tfPort.getText().trim();
            String account = tfAccount.getText().trim();

            if (StringUtils.isAllBlank(host) ||
                    StringUtils.isAllBlank(port) ||
                    StringUtils.isAllBlank(account)) {

                return;
            }
            ClientUI clientUI = new ClientUI(account);
            client = new ChatClient();
            client.setHost(host);
            client.setPort(Integer.parseInt(port));
            client.setAccount(account);
            client.setClientUI(clientUI);
            client.start();

            EventQueue.invokeLater(() -> {
                while (client.isWaiting()) {
                    if (client.isJoining()) {
                        clientUI.setVisible(true);

                        this.dispose();
                        break;
                    }
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException e1) {
                        e1.printStackTrace();
                    }
                }
            });
        });

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
                pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnMainLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnMainLayout.createSequentialGroup()
                                                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbHost, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lbPort, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lbAccount, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(tfPort)
                                                        .addComponent(tfAccount)
                                                        .addComponent(tfHost, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(pnMainLayout.createSequentialGroup()
                                                .addGap(96, 96, 96)
                                                .addComponent(lbTitle)))
                                .addContainerGap(74, Short.MAX_VALUE))
        );

        pnMainLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{lbAccount, lbHost, lbPort});

        pnMainLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{tfAccount, tfHost, tfPort});

        pnMainLayout.setVerticalGroup(
                pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnMainLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lbTitle)
                                .addGap(18, 18, 18)
                                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbHost)
                                        .addComponent(tfHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbPort)
                                        .addComponent(tfPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbAccount)
                                        .addComponent(tfAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnLogin)
                                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lbAccount;
    private javax.swing.JLabel lbHost;
    private javax.swing.JLabel lbPort;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel pnMain;
    private javax.swing.JTextField tfAccount;
    private javax.swing.JTextField tfHost;
    private javax.swing.JTextField tfPort;
    // End of variables declaration

    public void init() {
        java.awt.EventQueue.invokeLater(() ->
                this.setVisible(true)
        );
    }
}
